dist: bionic
sudo: required

language: c

addons:
  apt:
    packages:
      - automake
      - make
      - libtool
      - pkg-config
      - gcc
      - g++
      - git-core
      - luajit
      - libluajit-5.1-dev
      - uthash-dev
      - cppcheck

env:
  global:
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install g++-8 libstdc++-8-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90

install:
  - cd ../../
  - git clone --depth=1 git://github.com/kmarkus/uutils
  - git clone --depth=1 git://github.com/liblfds/liblfds6.1.1
  - git clone --depth=1 -b LUAUNIT_V3_3 git://github.com/bluebird75/luaunit
  # install uutils
  - cd uutils/
  - sudo make install
  - cd ..
  # install luaunit
  - sudo install -Dt /usr/share/lua/5.1/ luaunit/luaunit.lua
  # install liblfds
  - cd liblfds6.1.1
  - git -c user.name='travis' -c user.email='xxx' am ../kmarkus/microblx/liblfds/*.patch
  - ./bootstrap
  - ./configure --prefix=/usr/
  - make -j3
  - sudo make install
  - cd ..
    
script:
  - cd kmarkus/microblx
  - ./bootstrap
  - ./configure
  - make cppcheck
  - make -j3
  - sudo make install
  - ./run_tests.sh
  # test generating an out-of-tree block
  - ubx-genblock -d /tmp/testblock/ -c examples/blockmodels/block_model_example.lua
  - pushd /tmp/testblock/
  - ./bootstrap && ./configure && make && sudo make install
  - ubx-launch -t 1 -webif -c myblock.usc
  - popd
  # test generating an out-of-tree cpp block
  - ubx-genblock -cpp -d /tmp/testblock-cpp/ -c examples/blockmodels/block_model_example.lua
  - pushd /tmp/testblock-cpp/
  - ./bootstrap && ./configure && make && sudo make install
  - ubx-launch -t 1 -webif -c myblock.usc
  - popd
  # run the threshold example
  - ubx-launch -t 3 -s -check unconn_inports,unconn_outports -c examples/usc/threshold.usc
  # run the pid example
  - pushd /usr/local/share/ubx/examples/usc/pid/
  - ubx-launch -t 3 -s -check unconn_inports,unconn_outports -c pid_test.usc,ptrig_nrt.usc
  - popd
  # build and run tutorial
  # platform_2dof
  - ubx-genblock -c examples/platform/platform_2dof.lua -d /tmp/platform_2dof/
  - cp examples/platform/platform_2dof.c /tmp/platform_2dof/
  - pushd /tmp/platform_2dof/
  - ./bootstrap && ./configure && make && sudo make install
  - popd
  # platform_2dof_control
  - ubx-genblock -c examples/platform/platform_2dof_control.lua -d /tmp/platform_2dof_control/
  - cp examples/platform/platform_2dof_control.c /tmp/platform_2dof_control/
  - pushd /tmp/platform_2dof_control/
  - ./bootstrap && ./configure && make && sudo make install
  - popd
  # run the tutorial usc
  - ubx-launch -t 2 -c examples/platform/platform_launch/platform_2dof_and_control.usc
  # build the c-launch example
  - pushd examples/platform/platform_launch
  - autoreconf -i && ./configure && make
  - popd
  # build the minimal c-launch example and run it
  - pushd examples/C/
  - gcc -Wall -Werror c-launch.c -o c-launch -lubx
  - ./c-launch 1
